language: bash
services: docker

before_script:
  - echo "${docker_hub_access_token}" | docker login --username sohmc --password-stdin

script:
  - docker build . --file ./Dockerfile --tag sohmc/php-mysqli:7.4-apache
  - docker push sohmc/php-mysqli:7.4-apache
