language: bash
services: docker

env:
  - TAG=7.4.0-cli-buster
  - TAG=7.4-cli-buster
  - TAG=7-cli-buster
  - TAG=cli-buster
  - TAG=7.4.0-buster
  - TAG=7.4-buster
  - TAG=7-buster
  - TAG=buster
  - TAG=7.4.0-cli
  - TAG=7.4-cli
  - TAG=7-cli
  - TAG=cli
  - TAG=7.4.0
  - TAG=7.4
  - TAG=7
  - TAG=latest
  - TAG=7.4.0-apache-buster
  - TAG=7.4-apache-buster
  - TAG=7-apache-buster
  - TAG=apache-buster
  - TAG=7.4.0-apache
  - TAG=7.4-apache
  - TAG=7-apache
  - TAG=apache
  - TAG=7.4.0-fpm-buster
  - TAG=7.4-fpm-buster
  - TAG=7-fpm-buster
  - TAG=fpm-buster
  - TAG=7.4.0-fpm
  - TAG=7.4-fpm
  - TAG=7-fpm
  - TAG=fpm
  - TAG=7.4.0-zts-buster
  - TAG=7.4-zts-buster
  - TAG=7-zts-buster
  - TAG=zts-buster
  - TAG=7.4.0-zts
  - TAG=7.4-zts
  - TAG=7-zts
  - TAG=zts
  - TAG=7.4.0-cli-alpine3.10
  - TAG=7.4-cli-alpine3.10
  - TAG=7-cli-alpine3.10
  - TAG=cli-alpine3.10
  - TAG=7.4.0-alpine3.10
  - TAG=7.4-alpine3.10
  - TAG=7-alpine3.10
  - TAG=alpine3.10
  - TAG=7.4.0-cli-alpine
  - TAG=7.4-cli-alpine
  - TAG=7-cli-alpine
  - TAG=cli-alpine
  - TAG=7.4.0-alpine
  - TAG=7.4-alpine
  - TAG=7-alpine
  - TAG=alpine
  - TAG=7.4.0-fpm-alpine3.10
  - TAG=7.4-fpm-alpine3.10
  - TAG=7-fpm-alpine3.10
  - TAG=fpm-alpine3.10
  - TAG=7.4.0-fpm-alpine
  - TAG=7.4-fpm-alpine
  - TAG=7-fpm-alpine
  - TAG=fpm-alpine
  - TAG=7.4.0-zts-alpine3.10
  - TAG=7.4-zts-alpine3.10
  - TAG=7-zts-alpine3.10
  - TAG=zts-alpine3.10
  - TAG=7.4.0-zts-alpine
  - TAG=7.4-zts-alpine
  - TAG=7-zts-alpine
  - TAG=zts-alpine

before_script:
  - echo "${docker_hub_access_token}" | docker login --username sohmc --password-stdin
  - sed "s/{{TAG}}/$TAG/" ./.travis-ci/Dockerfile_Template > ./.travis-ci/Dockerfile

script:
  - docker build . --file ./.travis-ci/Dockerfile --tag sohmc/php-mysqli:$TAG
  - docker push sohmc/php-mysqli:$TAG
