name: Get Architecture for given Variant
description: Gets the supported architecture of the given image variant.
inputs:
  variant:
    description: variant to lookup
    required: true
outputs:
  architectures: 
    description: architectures that the variant supports
    value: ${{ steps.get-architectures.outputs.architectures }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-architectures
      run: |
        curl -kL -o php.json https://github.com/sohmc/docker-image-library-jsonizer/releases/download/latest/php
        echo VARIANT: ${{ inputs.variant }}
        ARCHITECTURES=$(jq -cr --arg VARIANT ${{ inputs.variant }} '.[$VARIANT].architectures' php.json)
        echo "Architectures: ${ARCHITECTURES}"
        echo "architectures=$ARCHITECTURES" >> $GITHUB_OUTPUT

    - uses: ./.github/workflows/build-matrix
      with:
        variant: ${{ inputs.variant }}
        architectures: ${{ steps.get-architectures.architectures }}