name: Docker Image CI

on: 
  push:
    branches:
      - github-workflows
  release:
    types: 
      - published

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [alpine, apache, buster, cli]
        # tags: [alpine, alpine3.12, apache, apache-buster, buster, cli, cli-alpine, cli-alpine3.12, cli-buster, fpm, fpm-alpine, fpm-alpine3.12, fpm-buster, latest, zts, zts-buster]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: | 
          echo "++++ Building ${TESTTAG} ++++"
          sed "s/{{TAG}}/$TAG/" ./.travis-ci/Dockerfile_Template > ./.travis-ci/Dockerfile
        env:
          TAG: ${{ matrix.tag }}

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./.travis-ci
          file: ./.travis-ci/Dockerfile
          tags: sohmc/php-mysqli:${{ matrix.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
