name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag sohmc/php-mysqli:7.4-apache
        docker push sohmc/php-mysqli:7.4-apache
