name: Docker Image CI

on: 
  push:
    branches:
      - github-workflows
  release:
    types: 
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: sohmc/php-mysqli
          tag_with_ref: true
