name: Multi-Platform Docker Image Build CI

on: 
  workflow_call:
    inputs:
      version: 
        type: string
        required: false
        default: '8.0'

jobs:
  get-php-variants:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.get-variants.outputs.variants }}

    steps:
      - name: Get variants
        id: get-variants
        run: |
          echo Getting Variants for version ${{ inputs.version }}
          curl -kL -o php.json https://github.com/sohmc/docker-image-library-jsonizer/releases/latest/download/php
          VARIANTS=$(jq -cr --ARG VERSION ${{ inputs.version }} '[.tags[].Directory | select(startswith($VERSION))]' php.json)
          echo Variants: ${VARIANTS}
          echo "variants=$VARIANTS" >> $GITHUB_OUTPUT
      
  get-variant-architectures:
    needs: get-php-variants
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        variants: ${{ fromJSON(needs.get-php-variants.outputs.variants) }}
        # variants: [ "8.0/alpine3.16/cli" ]
    uses: ./.github/workflows/build-image.yml 
    secrets: inherit
    with:
      variant: ${{ matrix.variants }}


