name: Multi-Platform Docker Image Build CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [building-in-docker-hub]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
  release:
    types: published
  schedule:
    # 4am every Saturday
    - cron: '0 4 * * 6'

env:
  REGISTRY_IMAGE: ${{ github.repository }}

jobs:
  get-php-variants:
    if: github.ref == 'xxx'
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.get-variants.outputs.variants }}

    steps:
      - name: Get variants
        id: get-variants
        run: |
          curl -kL -o php.json https://github.com/sohmc/docker-image-library-jsonizer/releases/download/latest/php
          VARIANTS=$(jq -cr 'keys | map(select(startswith("8.2") or startswith("8.1") or startswith("8.0")))' php.json)
          echo Variants: ${VARIANTS}
          echo "variants=$VARIANTS" >> $GITHUB_OUTPUT
      
  build-variant-images:
    runs-on: ubuntu-latest
    # needs: get-php-variants
    strategy:
      max-parallel: 1
      matrix:
        # variants: ${{ fromJSON(needs.get-php-variants.outputs.variants) }}
        variants: [ "8.0/alpine3.16/cli" ]
    steps:
      - uses: actions/checkout@v4

      - run: |
          ls -lRF
          cat ./.github/workflows/build-image.yml

      - name: Call Image Builder
        uses: ./ci/reusable-workflows/build-image
        with:
          variant: ${{ matrix.variants }}

