name: Docker Image CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [building-in-docker-hub]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
  release:
    types: published
  schedule:
    # 4am every Saturday
    - cron: '0 4 * * 6'

jobs:

  php-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [base]
        varients: [alpine]
        platform: [linux/amd64, linux/arm/v7, linux/arm64]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Dockerfile
        id: build_dockerfile
        run: |
          echo "VERSION: ${VERSION} - VARIENT: ${VARIENT} - PLATFORM: ${PLATFORM}"
          if [[ "$VERSION" == "base" ]]; then 
            TAG=$VARIENT
          else
            TAG=$VERSION-$VARIENT
          fi
          echo "::set-output name=tag::${TAG}"
          echo "++++ Building ${TAG} ++++"
          sed "s/{{TAG}}/$TAG/" ./ci/Dockerfile_Template > ./ci/Dockerfile
        env:
          VERSION: ${{ matrix.versions }}
          VARIENT: ${{ matrix.varients }}
          PLATFORM: ${{ matrix.platform }}
         

      # Multi-platform building: https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        id: docker_image_build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: ${{ matrix.platform }}
          file: ./ci/Dockerfile
          tags: sohmc/php-mysqli:${{ steps.build_dockerfile.outputs.tag }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Image Digest
        run: echo ${{ steps.docker_image_build.outputs.tag }}

