name: Docker Image CI

on: 
  push:
    branches:
      - github-workflows
  release:
    types: 
      - published

jobs:

  php-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [base]
        varients: [alpine, alpine3.12, apache, apache-buster, buster, cli, cli-alpine, cli-alpine3.12, cli-buster, fpm, fpm-alpine, fpm-alpine3.12, fpm-buster, latest, zts, zts-buster]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        id: build_dockerfile
        run: |
          echo "VERSION: ${VERSION} - VARIENT: ${VARIENT}"
          if [[ "$VERSION" == "base" ]]; then 
            TAG=$VARIENT
          else
            TAG=$VERSION-$VARIENT
          fi
          echo "::set-output name=tag::${TAG}"
          echo "++++ Building ${TAG} ++++"
          sed "s/{{TAG}}/$TAG/" ./.travis-ci/Dockerfile_Template > ./.travis-ci/Dockerfile
        env:
          VERSION: ${{ matrix.versions }}
          VARIENT: ${{ matrix.varients }}
         

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        id: docker_image_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./.travis-ci/Dockerfile
          tags: sohmc/php-mysqli:${{ steps.build_dockerfile.outputs.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_image_build.outputs.tag }}


  php-8:
    runs-on: ubuntu-latest
    needs: php-latest
    strategy:
      matrix:
        versions: [8, 8.0, 8.0.0]
        varients: [alpine, alpine3.12, apache, apache-buster, buster, cli, cli-alpine, cli-alpine3.12, cli-buster, fpm, fpm-alpine, fpm-alpine3.12, fpm-buster, zts, zts-buster]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        id: build_dockerfile
        run: |
          echo "VERSION: ${VERSION} - VARIENT: ${VARIENT}"
          if [[ "$VERSION" == "base" ]]; then 
            TAG=$VARIENT
          else
            TAG=$VERSION-$VARIENT
          fi
          echo "::set-output name=tag::${TAG}"
          echo "++++ Building ${TAG} ++++"
          sed "s/{{TAG}}/$TAG/" ./.travis-ci/Dockerfile_Template > ./.travis-ci/Dockerfile
        env:
          VERSION: ${{ matrix.versions }}
          VARIENT: ${{ matrix.varients }}
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        id: docker_image_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./.travis-ci/Dockerfile
          tags: sohmc/php-mysqli:${{ steps.build_dockerfile.outputs.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_image_build.outputs.tag }}


  php-7:
    runs-on: ubuntu-latest
    needs: php-latest
    strategy:
      matrix:
        versions: [7, 7.4]
        varients: [alpine, alpine3.12, apache, apache-buster, buster, cli, cli-alpine, cli-alpine3.12, cli-buster, fpm, fpm-alpine, fpm-alpine3.12, fpm-buster, zts, zts-buster]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        id: build_dockerfile
        run: |
          echo "VERSION: ${VERSION} - VARIENT: ${VARIENT}"
          if [[ "$VERSION" == "base" ]]; then 
            TAG=$VARIENT
          else
            TAG=$VERSION-$VARIENT
          fi
          echo "::set-output name=tag::${TAG}"
          echo "++++ Building ${TAG} ++++"
          sed "s/{{TAG}}/$TAG/" ./.travis-ci/Dockerfile_Template > ./.travis-ci/Dockerfile
        env:
          VERSION: ${{ matrix.versions }}
          VARIENT: ${{ matrix.varients }}
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: sohmc
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        id: docker_image_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./.travis-ci/Dockerfile
          tags: sohmc/php-mysqli:${{ steps.build_dockerfile.outputs.tag }}

      - name: Image Digest
        run: echo ${{ steps.docker_image_build.outputs.tag }}
