name: Testing Scheduled ENVs
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  schedule:
    - cron: '10 * * * *'
    - cron: '15 * * * *'
    - cron: '20 * * * *'

env:
  VERSION: ${{ ( github.event.schedule == '10 * * * *' && '8.2' ) || ( github.event.schedule == '15 * * * *' && '8.1' ) || ( github.event.schedule == '20 * * * *' && '8.0' ) ||  '8.2' }}

jobs:
  get-latest-commit:
    runs-on: ubuntu-latest
    steps:       
      - name: Inspect event
        run: |
          date
          echo "VERSION: $VERSION"
          echo "github.event.schedule: ${SCHEDULE}"
          echo "Event Name: ${GITHUB_EVENT_NAME}"
          cat ${GITHUB_EVENT_PATH}
        env:
          SCHEDULE: ${{ github.event.schedule }}

      - name: Get variants
        id: get-variants
        run: |
          echo Getting Variants for version ${VERSION}
          curl -kL -o php.json https://github.com/sohmc/docker-image-library-jsonizer/releases/latest/download/php
          VARIANTS=$(jq -cr --arg VERSION ${VERSION} '[.tags[].Directory | select(startswith($VERSION))]' php.json)
          echo Variants: ${VARIANTS}
          echo "variants=$VARIANTS" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ env.VERSION }}

