name: Testing

on:
  push: 

jobs:
  get-variant-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Get all tags for variant
        id: get_all_tags
        run: |
          curl -kL -o php.json https://github.com/sohmc/docker-image-library-jsonizer/releases/download/latest/php
          echo VARIANT: ${VARIANT}
          ALL_TAGS=$(jq -cr --arg VARIANT ${VARIANT} '.tags[] | select(.Directory == $VARIANT).Tags | map("-t " + .) | join(" ")' php.json)
          echo "All Tags: ${ALL_TAGS}"
          echo "all_tags=$ALL_TAGS >> $GITHUB_OUTPUT"
        env:
          VARIANT: "8.0/alpine3.16/cli"
      
      - name: Inspect Docker Image Tags
        working-directory: /tmp/digests
        run: |
          echo "All Tags: ${ALL_TAGS}"
          ls -l
          echo $(printf '${{ github.repository }}@sha256:%s ' *)
        env:
          ALL_TAGS: ${{ steps.get_all_tags.outputs.all_tags }}
